// Shared application state and DOM references.
export const state = {
  mode: 'play',
  data: {
    scenarios: [],
    characters: [],
    actions: [],
    events: [],
    abilities: [],
    tokens: [],
    rules: '',
  },
  selectedScenario: null,
  selectedCharacters: [],
  round: 1,
  victoryPoints: 0,
  drawSize: 1,
  handSize: 1,
  initiative: [],
  activeSubsection: 'scenario-selection',
  referenceFilter: 'all',
  initiativeEditMode: false,
  referenceTab: 'Scenarios',
  characterSelectionTab: null,
  latestEvent: null,
  referenceCharacterHouseTab: null,
  gameplayTab: 'Tracker',
  generateEventOnAdvance: false,
  generateEvents: false,
  generateNpcDancers: false,
  randomizeInitiative: false,
  maxSelectedCharacters: 2,
};

export const elements = {
  progressBar: document.getElementById("progressBar"),
  resetButton: document.getElementById('resetButton'),
  modeToggle: document.getElementById('modeToggle'),
  currentMode: document.getElementById('currentMode'),
  summaryText: document.getElementById('summaryText'),
  appContent: document.getElementById('appContent'),
};
